INFO     [2020-01-05 01:29:18] Scrapy 1.8.0 started (bot: gbavitore)
INFO     [2020-01-05 01:29:18] Versions: lxml 4.4.1.0, libxml2 2.9.9, cssselect 1.1.0, parsel 1.5.2, w3lib 1.21.0, Twisted 19.10.0, Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)], pyOpenSSL 19.0.0 (OpenSSL 1.1.1d  10 Sep 2019), cryptography 2.7, Platform Windows-7-6.1.7601-SP1
INFO     [2020-01-05 01:29:18] Overridden settings: {'AUTOTHROTTLE_DEBUG': True, 'AUTOTHROTTLE_ENABLED': True, 'AUTOTHROTTLE_MAX_DELAY': 3, 'BOT_NAME': 'gbavitore', 'CONCURRENT_REQUESTS': 8, 'CONCURRENT_REQUESTS_PER_DOMAIN': 16, 'CONCURRENT_REQUESTS_PER_IP': 16, 'COOKIES_ENABLED': False, 'DOWNLOAD_DELAY': 1.734, 'LOG_FILE': 'InstagramLog.log', 'LOG_FORMAT': '%(levelname)-8s [%(asctime)s] %(message)s', 'NEWSPIDER_MODULE': 'spiders', 'SPIDER_MODULES': ['spiders'], 'TELNETCONSOLE_ENABLED': False, 'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36 OPR/65.0.3467.72'}
INFO     [2020-01-05 01:29:18] Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.throttle.AutoThrottle']
INFO     [2020-01-05 01:29:18] Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
INFO     [2020-01-05 01:29:18] Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
CRITICAL [2020-01-05 01:32:41] Unhandled error in Deferred:
CRITICAL [2020-01-05 01:32:41] Unhandled error in Deferred:
CRITICAL [2020-01-05 01:32:41] 
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\crawler.py", line 86, in crawl
    self.engine = self._create_engine()
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\crawler.py", line 111, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\core\engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\core\scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\middleware.py", line 35, in from_settings
    mw = create_instance(mwcls, settings, crawler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\utils\misc.py", line 146, in create_instance
    return objcls(*args, **kwargs)
  File "C:\Users\ErshovAA\Documents\Python Scripts\CollectProcessData\Lesson6\pipelines.py", line 16, in __init__
    connection.geekbrains.authenticate('sysdba', 'masterkey')
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\database.py", line 1048, in authenticate
    connect=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\mongo_client.py", line 500, in _cache_credentials
    writable_preferred_server_selector)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\topology.py", line 214, in select_server
    address))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: gbubuntu.tk:27017: timed out
CRITICAL [2020-01-05 01:32:41] 
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\crawler.py", line 86, in crawl
    self.engine = self._create_engine()
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\crawler.py", line 111, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\core\engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\core\scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\middleware.py", line 35, in from_settings
    mw = create_instance(mwcls, settings, crawler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\utils\misc.py", line 146, in create_instance
    return objcls(*args, **kwargs)
  File "C:\Users\ErshovAA\Documents\Python Scripts\CollectProcessData\Lesson6\pipelines.py", line 16, in __init__
    connection.geekbrains.authenticate('sysdba', 'masterkey')
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\database.py", line 1048, in authenticate
    connect=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\mongo_client.py", line 500, in _cache_credentials
    writable_preferred_server_selector)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\topology.py", line 214, in select_server
    address))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: gbubuntu.tk:27017: timed out
CRITICAL [2020-01-05 01:32:41] Unhandled error in Deferred:
CRITICAL [2020-01-05 01:32:41] Unhandled error in Deferred:
CRITICAL [2020-01-05 01:32:41] 
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\crawler.py", line 86, in crawl
    self.engine = self._create_engine()
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\crawler.py", line 111, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\core\engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\core\scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\middleware.py", line 35, in from_settings
    mw = create_instance(mwcls, settings, crawler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\utils\misc.py", line 146, in create_instance
    return objcls(*args, **kwargs)
  File "C:\Users\ErshovAA\Documents\Python Scripts\CollectProcessData\Lesson6\pipelines.py", line 16, in __init__
    connection.geekbrains.authenticate('sysdba', 'masterkey')
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\database.py", line 1048, in authenticate
    connect=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\mongo_client.py", line 500, in _cache_credentials
    writable_preferred_server_selector)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\topology.py", line 214, in select_server
    address))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: gbubuntu.tk:27017: timed out
CRITICAL [2020-01-05 01:32:41] 
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\crawler.py", line 86, in crawl
    self.engine = self._create_engine()
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\crawler.py", line 111, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\core\engine.py", line 70, in __init__
    self.scraper = Scraper(crawler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\core\scraper.py", line 71, in __init__
    self.itemproc = itemproc_cls.from_crawler(crawler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\middleware.py", line 53, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\middleware.py", line 35, in from_settings
    mw = create_instance(mwcls, settings, crawler)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\utils\misc.py", line 146, in create_instance
    return objcls(*args, **kwargs)
  File "C:\Users\ErshovAA\Documents\Python Scripts\CollectProcessData\Lesson6\pipelines.py", line 16, in __init__
    connection.geekbrains.authenticate('sysdba', 'masterkey')
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\database.py", line 1048, in authenticate
    connect=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\mongo_client.py", line 500, in _cache_credentials
    writable_preferred_server_selector)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\topology.py", line 214, in select_server
    address))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymongo\topology.py", line 189, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: gbubuntu.tk:27017: timed out
